just/just/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from main.views import employer_login_view, seeker_login_view, home
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('searcher/', include('searcher.urls')),
    path('company/', include('company.urls')),
    path('employer/login/', employer_login_view, name='employer_login'),
    path('seeker/login/', seeker_login_view, name='seeker_login'),
    path('employer/', include('employer.urls')),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('create-resume/', include('resume.urls')),
    path('feedback/', include('feedback.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

just/searcher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import (register_seeker_step1,
                    register_seeker_step2,
                    register_seeker_step3,
                    edit_profile,
                    error_page,
                    vacancy_list,
                    vacancy_detail,
                    #save_vacancy,
                    toggle_save_vacancy,
                    profile_resume_saved_vacancies,
                    get_city_suggestions,
                    delete_saved_vacancy
                    )
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('register/step1/', register_seeker_step1, name='register_seeker_step1'),
    path('register/step2/', register_seeker_step2, name='register_seeker_step2'),
    path('register/step3/', register_seeker_step3, name='register_seeker_step3'),
    path('get_city_suggestions/', get_city_suggestions, name='get_city_suggestions'),
    path('get_city_id/', views.get_city_id, name='get_city_id'),


    path('profile/edit/', edit_profile, name='edit_profile'),
    path('profile/edit/error/', error_page, name='error_page'),
    path('profile/resumes/', views.profile_resume_list, name='profile_resume_list'),
    path('vacancies/', vacancy_list, name='vacancy_list'),
    path('vacancy/<slug:slug>/<int:vacancy_id>/', vacancy_detail, name='vacancy_detail'),
    #path('save-vacancy/<int:vacancy_id>/', save_vacancy, name='save_vacancy'),
    path('toggle-save-vacancy/<int:vacancy_id>/', toggle_save_vacancy, name='toggle_save_vacancy'),
    path('delete-saved-vacancy/<int:vacancy_id>/', delete_saved_vacancy, name='delete_saved_vacancy'),
    path('profile/saved-vacancies/', profile_resume_saved_vacancies, name='profile_resume_saved_vacancies'),
    path('resume/<int:pk>/delete/', views.delete_resume, name='delete_resume'),
    path('resume/<int:pk>/', views.resume_detail, name='resume_detail'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

just/searcher/models.py
from django.db import models
from django.conf import settings
from company.models import Vacancy





class SavedVacancy(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='saved_vacancies')
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, related_name='saved_by_users')
    saved_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} saved {self.vacancy.position.name}"

just/searcher/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from main.models import User, City
from main.validators import CustomSeekerPasswordValidator
import re
from django.core.files.base import ContentFile
import base64

import datetime

import logging
from django.contrib.auth import get_user_model
from django.contrib import messages
from main.utils import clean_phone


class PhoneVerificationForm(forms.Form):
    phone = forms.CharField(
        max_length=15,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'Номер телефону'})
    )

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        return clean_phone(phone)

class ConfirmationCodeForm(forms.Form):
    code = forms.CharField(
        max_length=6,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'Код підтвердження'})
    )

class SeekerRegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'Ім’я'})
    )
    last_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'Прізвище'})
    )
    middle_name = forms.CharField(
        max_length=30,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'По батькові'})
    )
    city_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'js_open form__input', 'placeholder': 'Місто'})
    )


    birthday = forms.DateField(
        required=False,
        widget=forms.SelectDateWidget(
            years=range(1900, 2024),
            attrs={'class': 'form__input'}
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form__input', 'placeholder': 'Пароль для входу'}
        ),
        help_text="Пароль має містити рівно 4 цифри.",
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form__input', 'placeholder': 'Повторити пароль'}
        ),
        help_text="Пароль має містити рівно 4 цифри.",
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'middle_name', 'city_name', 'birthday', 'password1', 'password2')

    def clean(self):
        cleaned_data = super().clean()
        city_name = cleaned_data.get('city_name')
        if city_name:
            try:
                city = City.objects.get(name__iexact=city_name)
                cleaned_data['city'] = city
            except City.DoesNotExist:
                self.add_error('city_name', 'Invalid city name.')
        return cleaned_data


    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Паролі не збігаються.")

        validator = CustomSeekerPasswordValidator()
        validator.validate(password2)

        return password2

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        validator = CustomSeekerPasswordValidator()
        validator.validate(password1)

        return password1

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = 'seeker'  # Явно встановлюємо роль пошуковця
        # Зберігаємо номер телефону із сесії
        if 'phone' in self.initial:
            user.phone = self.initial['phone']
        if commit:
            user.save()
        return user

class SelectDateWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        years = [('', 'Рік')] + [(year, year) for year in range(1950, datetime.datetime.now().year - 14)]
        months = [('', 'Місяць')] + [
            (1, 'Січень'), (2, 'Лютий'), (3, 'Березень'), (4, 'Квітень'),
            (5, 'Травень'), (6, 'Червень'), (7, 'Липень'), (8, 'Серпень'),
            (9, 'Вересень'), (10, 'Жовтень'), (11, 'Листопад'), (12, 'Грудень')
        ]
        days = [('', 'День')] + [(day, day) for day in range(1, 32)]

        widgets = [
            forms.Select(attrs={'class': 'form__input form__select create-resume__input-size-lg'}, choices=days),
            forms.Select(attrs={'class': 'form__input form__select create-resume__input-size-lg'}, choices=months),
            forms.Select(attrs={'class': 'form__input form__select create-resume__input-size-lg'}, choices=years),
        ]
        super().__init__(widgets, attrs)

    def decompress(self, value):
        if value:
            if isinstance(value, str):
                try:
                    value = datetime.datetime.strptime(value, '%Y-%m-%d')
                except ValueError:
                    return [None, None, None]
            return [value.day, value.month, value.year]
        return [None, None, None]

    def compress(self, values):
        if values:
            try:
                day, month, year = values
                if day and month and year:
                    return f"{year}-{month:02d}-{day:02d}"
            except ValueError:
                pass
        return None

    def value_from_datadict(self, data, files, name):
        day = data.get(f'{name}_0')
        month = data.get(f'{name}_1')
        year = data.get(f'{name}_2')
        if day and month and year:
            return f'{year}-{month}-{day}'
        return None


User = get_user_model()
class UserProfileForm(forms.ModelForm):
    city_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'js_open form__input input-size-lg', 'placeholder': 'Місто'})
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'city_name', 'birthday', 'phone', 'email', 'avatar']
        widgets = {
            'birthday': SelectDateWidget(),
            'first_name': forms.TextInput(attrs={'class': 'form__input input-size-lg'}),
            'last_name': forms.TextInput(attrs={'class': 'form__input input-size-lg'}),
            'phone': forms.TextInput(attrs={'class': 'form__input input-size-lg'}),
            'email': forms.EmailInput(attrs={'class': 'form__input input-size-lg'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form__input input-size-lg'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.city:
            self.fields['city_name'].initial = self.instance.city.name

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        return clean_phone(phone)

    def clean(self):
        cleaned_data = super().clean()
        city_name = cleaned_data.get('city_name')
        if city_name:
            try:
                city = City.objects.get(name__iexact=city_name)
                cleaned_data['city'] = city
            except City.DoesNotExist:
                self.add_error('city_name', 'Invalid city name.')
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        cropped_avatar = self.data.get('cropped_avatar')
        if cropped_avatar:
            format, imgstr = cropped_avatar.split(';base64,')
            ext = format.split('/')[-1]
            data = ContentFile(base64.b64decode(imgstr), name=f'avatar.{ext}')
            user.avatar = data
        if commit:
            user.save()
        return user


class VacancySearchForm(forms.Form):
    title = forms.CharField(max_length=100, required=False, label='Назва вакансії', widget=forms.TextInput(attrs={
        'id': 'id_position', 'class': 'search-location__input js_open', 'placeholder': 'Менеджер'
    }))
    city = forms.CharField(max_length=100, required=False, label='Місто', widget=forms.TextInput(attrs={
        'id': 'id_city', 'class': 'search-location__select js_open', 'placeholder': 'Вся Україна'
    }))

just/searcher/templates/searcher/personal-2.html
{% extends "main/base.html" %}
{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'main/css/personal.css' %}"/>
{% endblock %}
{% block content %}
<div class="wrapper">
    <main>
        <div class="container">
            <div class="personal__inner">
                <div class="title-wrapper-start">
                    <h1 class="title-xl">Мій акаунт</h1>
                    <a class="link-sm" href="#">Дивитися публічний профіль</a>
                </div>

                <div class="personal__content-wrapper">
                    <aside class="personal__content-left">
                        <div class="personal__content-left-wrapper">
                            <a href="{% url 'edit_profile' %}"><p class="aside-subtitle subtitle">Налаштування профілю</p></a>
                            <nav>
                                <ul class="aside-nav__list">
                                    <li class="aside-nav__list-item text-medium-18 aside-nav__active"><a href="{% url 'profile_resume_list' %}">Мої резюме</a></li>
                                    <li class="aside-nav__list-item text-medium-18"><a href="#">Історія відгуків</a></li>
                                </ul>
                                <div class="aside-nav__line"></div>
                                <ul class="aside-nav__list">
                                    <li class="aside-nav__list-item text-medium-18">
                                        <a href="#">Рекомендовані вакансії</a>
                                        <p class="vacancy-info__item-value">12</p>
                                    </li>
                                    <li class="aside-nav__list-item text-medium-18">
                                        <a href="{% url 'profile_resume_saved_vacancies' %}">Збережені вакансії</a>
                                        <p class="vacancy-info__item-value">4</p>
                                    </li>
                                </ul>
                            </nav>
                            <div class="personal__logout__link-wrapper">
                                <a href="#" class="logout__link text-medium-18">
                                    <img
                                            src="../../images/log-in-red.svg"
                                            alt="search"
                                            class="search__img"
                                    />Вийти</a
                                >
                            </div>
                        </div>
                    </aside>
                    <section class="personal__content-right">
                        <ul class="personal__vacancy-list">
                            {% for resume_data in resume_list %}
                            <li class="personal__vacancy-item">
                                <a href="{% url 'resume_detail' resume_data.pk %}">
                                <div class="personal__vacancy-item-left">
                                    <div class="personal__item-title-wrapper">
                                        <h3 class="personal__vacancy-title">
                                            {% for position in resume_data.resume.desired_positions.all %}
                                            {{ position.name }}{% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                        </h3>
                                        <p class="personal__item-title-text">Оновлено {{ resume_data.time_since_modified }} тому</p>
                                    </div>
                                </div>
                                </a>
                                <div class="personal__title-icon-wrapper">
                                    <div class="personal__item-info-wrapper">
                                        <div class="personal__item-info">
                                            <p class="subtitle-text">250</p>
                                            <p class="subtitle-description">показів</p>
                                        </div>
                                        <div class="personal__item-info">
                                            <p class="subtitle-text">57</p>
                                            <p class="subtitle-description">переглядів</p>
                                        </div>
                                    </div>
                                    <img
                                            src="{% static 'main/images/edit.svg' %}"
                                            alt="edit"
                                            class="personal__title-edit-icon"
                                    />
                                    <form action="{% url 'delete_resume' resume_data.pk %}" method="post">
                                        {% csrf_token %}
                                        <button class="delete-photo__btn btn-transparent__delete" type="submit" name="delete_avatar" value="1">
                                        <img
                                            class="more-vertical-icon"
                                            src="{% static 'main/images/delete.svg' %}"
                                            alt="more-vertical"
                                        />
                                        </button>
                                    </form>
                                </div>
                            </li>
                        {% endfor %}
                        </ul>
                        <a href="{% url 'create_resume' %}">
                        <button class="add-btn-item add-btn-icon personal__btn-add-resume btn-transparent">
                            Cтворити ще одне резюме
                        </button>
                        </a>
                    </section>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

just/searcher/templates/searcher/registration-error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Помилка реєстрації</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'main/css/reset.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}"/>
</head>
<body>
<div class="wrapper">
    <main class="main">
        <div class="container">
           <section class="registration">
               <div class="registration-content">
                   <h3 class="form__title">Помилка реєстрації</h3>
                   <p class="form__subtitle">Виникла помилка під час реєстрації. Будь ласка, спробуйте ще раз.</p>
                   {% if form_errors %}
                       <ul class="form__errors">
                           {% for field, errors in form_errors.items %}
                               <li>{{ field }}: {{ errors|join:", " }}</li>
                           {% endfor %}
                       </ul>
                   {% endif %}
                   <a href="{% url 'register_seeker_step1' %}" class="form__submit-btn btn-color">Повернутись до реєстрації</a>
               </div>
           </section>
        </div>
    </main>
</div>
<script src="{% static 'main/index.js' %}"></script>
</body>
</html>

just/searcher/templates/searcher/registration-step-2.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Головна</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'main/css/reset.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}"/>
</head>
<body>
<div class="wrapper">
    <main class="main">
        <div class="container">
           <section class="registration">
               <div class="registration-content">
                   <div class="stepper-wrapper">
                       <div class="stepper-item">
                           <div class="step-counter done"><img class="check-mark" src="{% static 'images/check-mark.svg' %}" alt="#"></div>
                           <div class="step-name">Номер телефону</div>
                       </div>
                       <div class="stepper-item step-completed">
                           <div class="step-counter">2</div>
                           <div class="step-name">Підтвердження</div>
                       </div>
                       <div class="stepper-item">
                           <div class="step-counter">3</div>
                           <div class="step-name">Особисті дані</div>
                       </div>
                   </div>
                   <h3 class="form__title">Реєстрація</h3>
                   <p class="form__subtitle">На ваш номер телефону надіслано код</p>
                   <form method="post" action="{% url 'register_seeker_step2' %}" class="form">
                       {% csrf_token %}
                       <div class="form__input-wrapper-registration-top-24">

                           {{ form.code }}
                       </div>
                       <p class="form__input-text">Відправити повторно через 57с.</p>
                       <div class="form__double-input-wrapper">
                           <a href="#" class="form__link-back btn-transparent">Назад</a>
                           <input type="submit" id="continue" name="continue" class="form__submit-btn btn-color" value="Продовжити">
                       </div>
                   </form>
               </div>
           </section>
        </div>
    </main>
</div>
<script src="{% static 'main/index.js' %}"></script>
</body>
</html>

just/searcher/templates/searcher/registration-step-3.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8"/>
    <title>Головна</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
    />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>


    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link rel="stylesheet" href="{% static 'main/css/reset.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}"/>
</head>
<body>
<div class="wrapper">
    <main class="main">
        <div class="container">
           <section class="registration">
               <div class="registration-content">
                   <div class="stepper-wrapper">
                       <div class="stepper-item">
                           <div class="step-counter done"><img class="check-mark" src="{% static 'main/images/check-mark.svg' %}" alt="#"></div>
                           <div class="step-name">Номер телефону</div>
                       </div>
                       <div class="stepper-item">
                           <div class="step-counter done"><img class="check-mark" src="{% static 'main/images/check-mark.svg' %}" alt="#"></div>
                           <div class="step-name">Підтвердження</div>
                       </div>
                       <div class="stepper-item step-completed">
                           <div class="step-counter">3</div>
                           <div class="step-name">Особисті дані</div>
                       </div>
                   </div>
                   <h3 class="form__title">Реєстрація</h3>
                   <p class="form__subtitle">Введіть свої особисті дані, щоб завершити реєстрацію</p>
                   <form method="post" action="{% url 'register_seeker_step3' %}" class="form">
                       {% csrf_token %}

                       <div class="form__input-wrapper">
                            <label for="name" class="text-medium-16">Введіть імʼя</label>
                            {{ form.first_name }}
                       </div>
                       <div class="form__input-wrapper">
                            <label for="name2" class="text-medium-16">Введіть прізвище</label>
                            {{ form.last_name }}
                       </div>
                       <div class="form__input-wrapper_city">
                            <label for="city" class=text-medium-16l">Введіть місто</label>
                            {{ form.city_name }}
                        <input type="hidden" name="city_id" id="id_city_id">
                        <div id="city_not_found" style="display:none;color:red;">Місто не знайдено</div>
                       </div>

                       <div class="form__input-wrapper">
                            <label for="pas1" class="text-medium-16">Пароль</label>
                            {{ form.password1 }}
                       </div>
                       <div class="form__input-wrapper">
                            <label for="pas5" class="text-medium-16">Повторіть пароль</label>
                            {{ form.password2 }}
                       </div>
                       <div class="form__double-input-wrapper">
                           <a href="{% url 'register_seeker_step2' %}" class="form__link-back btn-transparent">Назад</a>
                           <input type="submit" class="form__submit-btn btn-color" value="Створити акаунт">
                       </div>
                   </form>
               </div>
           </section>
        </div>
    </main>
</div>
<script src="{% static 'main/js/city_autocomplete.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
<script src="{% static 'main/js/messages-error.js' %}"></script>
<script>
    $(document).ready(function(){
        $('#id_city_name').autocomplete({
            source: function(request, response) {
                $.ajax({
                    url: "{% url 'get_city_suggestions' %}",
                    dataType: "json",
                    data: {
                        term: request.term
                    },
                    success: function(data) {
                        response($.map(data, function(item) {
                            return {
                                label: item.name,
                                value: item.name,
                                id: item.id
                            };
                        }));
                    }
                });
            },
            minLength: 2,
            select: function(event, ui) {
                $('#id_city_name').val(ui.item.value);
                $('#id_city_id').val(ui.item.id);
                $('#city_not_found').hide();
            },
            change: function(event, ui) {
                if (!ui.item) {
                    $('#id_city_id').val('');
                }
            },
            response: function(event, ui) {
                if (ui.content.length === 0) {
                    $('#city_not_found').show();
                } else {
                    $('#city_not_found').hide();
                }
            },
            open: function(event, ui) {
                var $input = $(event.target),
                    $wrapper = $input.closest('.js_open'),
                    wrapperWidth = $wrapper.outerWidth();

                $input.autocomplete("widget").css('width', wrapperWidth + 'px');
            },
            classes: {
                "ui-autocomplete": "search-location__select-list",
                "ui-menu-item": "search-location__select-item"
            },
            appendTo: '.form__input-wrapper_city'
        });

        $('#id_city_name').on('blur', function() {
            var cityName = $(this).val();
            if (cityName) {
                $.ajax({
                    url: "{% url 'get_city_suggestions' %}",
                    dataType: "json",
                    data: {
                        term: cityName
                    },
                    success: function(data) {
                        var cityFound = false;
                        $.each(data, function(index, item) {
                            if (item.name.toLowerCase() === cityName.toLowerCase()) {
                                $('#id_city_id').val(item.id);
                                cityFound = true;
                                $('#city_not_found').hide();
                                return false;
                            }
                        });
                        if (!cityFound) {
                            $('#city_not_found').show();
                            $('#id_city_id').val('');
                        }
                    }
                });
            }
        });

        // Function to display Toastify notifications
        function showCToast(type, message) {
            /*
            type: info, success, error, default;
            message: message to be displayed.
            */
            const colorMap = {
                "info": '#63B3ED',
                "success": '#2dce89',
                "error": '#f5365c',
                "default": "#20c997"
            };

            const color = colorMap[type] || colorMap["default"];

            // Configure and display the toast notification
            Toastify({
                text: message,
                duration: 3000,
                className: type,
                close: true,
                gravity: "top",       // `top` or `bottom`
                position: "right",   // `left`, `center` or `right`
                stopOnFocus: true,    // Prevent dismissing of toast on hover
                style: {
                    background: color,
                },
                escapeMarkup: false,   // Render HTML tags in the notification
            }).showToast();
        }

        // Extract Django messages and display them using Toastify
        const customMessages = [
            {% for message in messages %}
                {
                    "tags": "{{ message.tags|default:''|escapejs }}",
                    "message": '{{ message.message|default:''|escapejs }}'
                }{% if not forloop.last %},{% endif %}
            {% endfor %}
        ];

        // Debugging: Log messages to the console
        console.log(customMessages);

        // Display each custom message using Toastify
        customMessages.forEach(message => {
            showCToast(message.tags, message.message);
        });
    });
    </script>
</body>
</html>