just/employer/urls.py
from django.urls import path
from .views import register_employer_step1, register_employer_step2, register_employer_step3, registration_error, edit_profile, profile_vacancy_list
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('register/step1/', register_employer_step1, name='register_employer_step1'),
    path('register/step2/', register_employer_step2, name='register_employer_step2'),
    path('register/step3/', register_employer_step3, name='register_employer_step3'),
    path('register/error/', registration_error, name='registration_error'),
    path('profile/edit/', edit_profile, name='employer_profile'),
    path('profile/vacancy/', profile_vacancy_list, name='profile_vacancy_list'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

just/just/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from main.views import employer_login_view, seeker_login_view, home
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('searcher/', include('searcher.urls')),
    path('company/', include('company.urls')),
    path('employer/login/', employer_login_view, name='employer_login'),
    path('seeker/login/', seeker_login_view, name='seeker_login'),
    path('employer/', include('employer.urls')),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('create-resume/', include('resume.urls')),
    path('feedback/', include('feedback.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

just/company/models.py
from django.db import models
from django.conf import settings  # Це використовується для посилання на модель User
from django.utils.text import slugify
from django.utils import timezone
from main.choices import EDUCATION_LEVEL_CHOICES
from ckeditor.fields import RichTextField


class Company(models.Model):
    EMPLOYEE_CHOICES = [
        (10, 'До 10 працівників '),
        (50, 'Від 10 до 50 працівників'),
        (100, 'Від 50 до 100 працівників'),
        (250, 'Від 100 до 250 працівників'),
        (500, 'Більше 500 працівників'),
    ]

    name = models.CharField(max_length=255, verbose_name="Назва")
    number_of_employees = models.IntegerField(choices=EMPLOYEE_CHOICES, verbose_name="Кількість працівників")
    logo = models.ImageField(upload_to='logos/', verbose_name="Логотип")
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, limit_choices_to={'role': 'employer'}, on_delete=models.CASCADE, verbose_name="Адміністратор", related_name='administered_companies')
    description = models.TextField(null=True, blank=True, verbose_name="Опис")
    has_link = models.BooleanField(default=False, verbose_name="Посилання")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")

    def __str__(self):
        return self.name


class JobCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name="Назва")
    slug = models.SlugField(max_length=255, unique=True, blank=True, verbose_name="Слаг")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class JobPositionGroup(models.Model):
    name = models.CharField(max_length=255, verbose_name="Назва")

    def __str__(self):
        return self.name


class JobPosition(models.Model):
    name = models.CharField(max_length=255, verbose_name="Назва")
    name_ru = models.CharField(max_length=255, verbose_name="Назва на російській мові")
    slug = models.SlugField(max_length=255, unique=True, blank=True, verbose_name="Слаг")
    categories = models.ManyToManyField(JobCategory, related_name="job_positions_by_category", verbose_name="Категорії")
    groups = models.ManyToManyField(JobPositionGroup, related_name="job_positions_by_group", verbose_name="Групи")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    image = models.ImageField(upload_to='articles/', verbose_name='Картинка')
    author = models.CharField(max_length=255, verbose_name='Автор')
    author_position = models.CharField(max_length=255, verbose_name='Посада автора')
    publication_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Перегляди')

    def __str__(self):
        return self.title


class ArticleSection(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Текст')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='sections', verbose_name='Стаття')

    def __str__(self):
        return self.title


class CommentArticle(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments', verbose_name='Користувач')
    date_time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')

    def __str__(self):
        return self.text[:20]  # Повертає перші 20 символів коментаря


class Hashtag(models.Model):
    name = models.CharField(max_length=50, verbose_name="Хештег")

    def __str__(self):
        return self.name


class Vacancy(models.Model):
    EMPLOYMENT_TYPE_CHOICES = [
        ('full', 'Повна зайнятісь'),
        ('part', 'Неповна зайнятісь'),
        ('shift', 'Позмінна робота'),
    ]

    WORK_TYPE_CHOICES = [
        ('internship', 'Стажування/практика'),
        ('remote', 'Відалена робота'),
        ('office', 'Робота в офісі'),
        ('hybrid', 'Гібридна робота'),
    ]

    STATUS_CHOICES = [
        ('standard', 'Стандарт'),
        ('standard_plus', 'Стандарт плюс'),
        ('hot', 'Гаряча'),
        ('hidden', 'Прихована'),
    ]

    EXPERIENCE_CHOICES = [
        ('no_experience', 'Можна без досвіду'),
        ('preferred_experience', 'Досвід буде перевагою'),
        ('one_year', 'Досвід від 1-го року'),
        ('two_years', 'Досвід від 2-х років'),
        ('more_than_five_years', 'Досвід більше 5 років'),
    ]

    SCHEDULE_CHOICES = [
        ('standard_5_2', 'Стандартний графік 5/2'),
        ('shift_4_4', 'Позмінний графік 4/4'),
        ('shift_2_2_4', 'Позмінний графік 2/2/4'),
        ('shift_4_2', 'Позмінний графік 4/2'),
        ('duty_1_3', 'Чергування доба/3 вихідних'),
        ('floating', 'Плаваючий графік'),
        ('free', 'Вільний графік'),
        ('part_time', 'Підробіток (не повний день)'),
    ]

    position = models.ForeignKey(JobPosition, on_delete=models.CASCADE, related_name='vacancies', verbose_name="Посада")
    position_comment = models.CharField(max_length=30, verbose_name="Коментар до посади", blank=True, null=True)
    city = models.ForeignKey('main.City', on_delete=models.CASCADE, verbose_name="Місто")
    address = models.CharField(max_length=255, verbose_name="Адреса", blank=True, null=True)
    phone_number = models.CharField(max_length=15, verbose_name="Номер телефону", blank=True, null=True)
    min_salary = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Зарплата мін", blank=True, null=True)
    max_salary = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Зарплата макс", blank=True, null=True)
    hashtags = models.ManyToManyField(Hashtag, verbose_name="Хештеги", blank=True)
    employment_type = models.CharField(max_length=10, choices=EMPLOYMENT_TYPE_CHOICES, verbose_name="Тип зайнятості",
                                       blank=True, null=True)
    education_level = models.CharField(max_length=20, choices=EDUCATION_LEVEL_CHOICES)
    description = models.TextField(verbose_name="Опис")
    social_networks = models.BooleanField(default=False, verbose_name="Соц.Мережі")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name="Компанія")
    publication_date = models.DateTimeField(default=timezone.now, verbose_name="Дата та час публікації")
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, verbose_name="Статус")
    view_count = models.PositiveIntegerField(default=0, verbose_name="Кількість переглядів")
    experience = models.CharField(max_length=20, choices=EXPERIENCE_CHOICES, verbose_name="Досвід роботи",
                                  default='no_experience')
    schedule = models.CharField(max_length=20, choices=SCHEDULE_CHOICES, verbose_name="Графік роботи",
                                default='standard_5_2')

    def __str__(self):
        return f"{self.position} at {self.company}"


class VacancyLanguage(models.Model):
    BEGINNER = 'beginner'
    BASIC = 'basic'
    INTERMEDIATE = 'intermediate'
    ADVANCED = 'advanced'
    NATIVE = 'native'
    PROFICIENCY_LEVEL_CHOICES = [
        (BEGINNER, 'Початківець'),
        (BASIC, 'Базовий рівень'),
        (INTERMEDIATE, 'Впевнений користувач'),
        (ADVANCED, 'Вільно'),
        (NATIVE, 'Рідна'),
    ]

    language = models.ForeignKey('resume.Language', on_delete=models.CASCADE, related_name='vacancy_languages')
    proficiency_level = models.CharField(max_length=20, choices=PROFICIENCY_LEVEL_CHOICES)
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, related_name='vacancy_languages')

    def __str__(self):
        return f'{self.language.name or ""} - {self.get_proficiency_level_display() or ""}'.strip()

    class Meta:
        verbose_name = 'Vacancy Language'
        verbose_name_plural = 'Vacancy Languages'

just/employer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
import base64
from main.models import User, City
from main.validators import EmployerPasswordValidator
from django.contrib.auth import get_user_model
from searcher.forms import SelectDateWidget

class EmailVerificationForm(forms.Form):
    email = forms.EmailField(
        max_length=255,
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form__input', 'placeholder': 'Email'})
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('Цей email вже зареєстрований.')
        return email

class EmailConfirmationCodeForm(forms.Form):
    code = forms.CharField(
        max_length=4,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'Код підтвердження'})
    )

class EmployerRegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'Ім’я'})
    )
    last_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'Прізвище'})
    )
    middle_name = forms.CharField(
        max_length=30,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'По батькові'})
    )
    city_name = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'js_open form__input', 'placeholder': 'Місто'})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form__input', 'placeholder': 'Пароль для входу'}
        ),
        help_text="Пароль має містити мінімум 8 символів.",
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form__input', 'placeholder': 'Повторити пароль'}
        ),
        help_text="Пароль має містити мінімум 8 символів.",
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'middle_name', 'city_name', 'password1', 'password2')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Паролі не збігаються.")

        validator = EmployerPasswordValidator()
        validator.validate(password2)

        return password2

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        validator = EmployerPasswordValidator()
        validator.validate(password1)

        return password1

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = 'employer'  # Явно встановлюємо роль роботодавця
        user.email = self.cleaned_data.get('email')
        if commit:
            user.save()
        return user



User = get_user_model()
class UserProfileForm(forms.ModelForm):
    city_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'js_open form__input input-size-lg', 'placeholder': 'Місто'})
    )
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'city_name', 'birthday', 'phone', 'email', 'avatar']
        widgets = {
            'birthday': SelectDateWidget(),
            'first_name': forms.TextInput(attrs={'class': 'form__input input-size-lg'}),
            'last_name': forms.TextInput(attrs={'class': 'form__input input-size-lg'}),

            'phone': forms.TextInput(attrs={'class': 'form__input input-size-lg'}),
            'email': forms.EmailInput(attrs={'class': 'form__input input-size-lg'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form__input input-size-lg'}),
        }


    def save(self, commit=True):
        user = super().save(commit=False)
        cropped_avatar = self.data.get('cropped_avatar')
        if cropped_avatar:
            format, imgstr = cropped_avatar.split(';base64,')
            ext = format.split('/')[-1]
            data = ContentFile(base64.b64decode(imgstr), name=f'avatar.{ext}')
            user.avatar = data
        if commit:
            user.save()
        return user

just/employer/templates/employer/personal-2.html
{% extends "main/base.html" %}
{% load static %}
{% load filters %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Особистий кабінет</title>
    {% block extra_styles %}
    <link rel="stylesheet" href="{% static 'main/css/personal.css' %}"/>
    {% endblock %}
</head>
<body>
<div class="wrapper">
    {% block content %}
    <main>
        <div class="container">
            <div class="personal__inner">
                <div class="title-wrapper-start">
                    <h1 class="title-xl">Мій акаунт</h1>
                </div>

                <div class="personal__content-wrapper">
                    <aside class="personal__content-left">
                        <div class="personal__content-left-wrapper">
                            <p class="aside-subtitle subtitle">Налаштування профілю</p>
                            <nav>
                                <ul class="aside-nav__list">
                                    <li class="aside-nav__list-item text-medium-18 aside-nav__active">
                                        <a href="{% url 'profile_vacancy_list' %}">Вакансії</a>
                                        <p class="vacancy-info__item-value">3</p>
                                    </li>
                                    <li class="aside-nav__list-item text-medium-18 ">
                                        <a href="{% url 'employer_feedback_list' %}">Відгуки</a>
                                        <p class="vacancy-info__item-value">123</p>
                                    </li>
                                </ul>
                                <div class="aside-nav__line"></div>
                                <ul class="aside-nav__list">
                                    <li class="aside-nav__list-item text-medium-18">
                                        <a href="#">Потенційни Кандидати</a>
                                        <p class="vacancy-info__item-value">430</p>
                                    </li>
                                    <li class="aside-nav__list-item text-medium-18">
                                        <a href="#">Збережені Кандидати</a>
                                        <p class="vacancy-info__item-value">12</p>
                                    </li>
                                </ul>
                                <div class="aside-nav__line"></div>
                                <ul class="aside-nav__list">
                                    <li class="aside-nav__list-item text-medium-18">
                                        <a href="#">Аналітика</a>
                                    </li>
                                    <li class="aside-nav__list-item text-medium-18">
                                        <a href="#">Оплата</a>
                                    </li>
                                    <li class="aside-nav__list-item text-medium-18">
                                        <a href="#">Реквізити</a>
                                    </li>
                                </ul>
                            </nav>
                            <div class="personal__logout__link-wrapper">
                                <a href="{% url 'logout' %}" class="logout__link text-medium-18">
                                    <img
                                            src="{% static 'main/images/log-in.svg' %}"
                                            alt="search"
                                            class="search__img"
                                    />Вийти</a
                                >
                            </div>
                        </div>
                    </aside>
                    <section class="personal__content-right">
                        <div class="personal__filter-block">
                            <form method="get" action="{% url 'profile_vacancy_list' %}">
                                <ul class="user__actions">
                                    <li class="user__actions-item">
                                        <label class="user__actions-btn-label">
                                            <input type="radio" name="status" value="active" class="user__actions-radio" {% if status == 'active' %}checked{% endif %} onchange="this.form.submit();">
                                            <span class="user__actions-btn">Активні ({{active_vacancies_count}})</span>
                                        </label>
                                    </li>
                                    <li class="user__actions-item">
                                        <label class="user__actions-btn-label">
                                            <input type="radio" name="status" value="closed" class="user__actions-radio" {% if status == "closed" %}checked{% endif %} onchange="this.form.submit();">
                                            <span class="user__actions-btn">Закриті ({{closed_vacancies_count}})</span>
                                        </label>
                                    </li>
                                </ul>
                            </form>
                            <div class="search__filter">
                                <img src="{% static 'images/sort.svg' %}" alt="filter" class="search__filter-img">
                                <button class="search__filter-btn">Спочатку нові</button>
                            </div>
                        </div>
                        <ul class="personal__vacancy-list">
                            {% for vacancy in vacancies %}
                            <li class="personal__vacancy-item">
                                <div class="personal__vacancy-item-left">
                                    <div class="personal__item-title-wrapper">
                                        <h3 class="personal__vacancy-title">{{ vacancy.position }}</h3>
                                        <p class="personal__item-title-text">Розміщено {{ vacancy.publication_date|date:"d.m.Y" }} {{vacancy.get_status_display}}</p>
                                    </div>
                                </div>
                                <div class="personal__vacancy-item-right">
                                    <div class="personal__item-info-inner">
                                        <div class="personal__item-info">
                                            <p class="subtitle-text">250</p>
                                            <p class="subtitle-description">показів</p>
                                        </div>
                                        <div class="personal__item-info">
                                            <p class="subtitle-text">{{ vacancy.feedback_count }}</p>
                                            <p class="subtitle-description">відгуків</p>
                                        </div>
                                        <div class="personal__item-info">
                                            <p class="subtitle-text">{{ vacancy.view_count|intspace }}</p>
                                            <p class="subtitle-description">переглядів</p>
                                        </div>
                                    </div>
                                    <div class="personal__title-icon-wrapper">
                                        <img src="{% static 'main/images/edit.svg' %}" alt="edit" class="personal__title-edit-icon"/>
                                        <img class="more-vertical-icon" src="{% static 'main/images/delete-red.svg' %}" alt="more-vertical"/>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                        <a href="{% url 'create_vacancy' %}">
                            <button class="personal__btn-add-resume btn-transparent text-medium-16-light">
                                <img src="{% static 'images/add-circle-dark.svg' %}" alt="add-circle">
                                Cтворити ще одну вакансію
                            </button>
                        </a>
                        <div class="vacancies-page__pagination">
                            <div class="pagination__block">
                                <div class="pagination">
                                    <span class="step-links">

                                        <!-- Перша сторінка -->
                                        <a href="?page=1{% if status %}&status={{ status }}{% endif %}"
                                           class="{% if vacancies.number == 1 %}active{% endif %}">
                                           &laquo; 1
                                        </a>

                                        {% if show_first_dots %}
                                            <span>...</span>
                                        {% endif %}

                                        <!-- Попередні сторінки -->
                                        {% for page in pages %}
                                            {% if page > 1 and page < total_pages %}
                                                <a href="?page={{ page }}{% if status %}&status={{ status }}{% endif %}"
                                                   class="{% if page == vacancies.number %}active{% endif %}">
                                                   {{ page }}
                                                </a>
                                            {% endif %}
                                        {% endfor %}

                                        {% if show_last_dots %}
                                            <span>...</span>
                                        {% endif %}


                                        <!-- Остання сторінка -->
                                        <a href="?page={{ total_pages }}{% if status %}&status={{ status }}{% endif %}"
                                           class="{% if vacancies.number == total_pages %}active{% endif %}">{{ total_pages }} &raquo;</a>

                                    </span>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </main>
    {% endblock %}
</div>
<script src="../../index.js"></script>
</body>
</html>

just/employer/templates/employer/registration-error.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Помилка реєстрації</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'main/css/reset.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}"/>
</head>
<body>
<div class="wrapper">
    <main class="main">
        <div class="container">
           <section class="registration">
               <div class="registration-content">
                   <h3 class="form__title">Помилка реєстрації</h3>
                   <p class="form__subtitle">Виникла помилка під час реєстрації. Будь ласка, спробуйте ще раз.</p>
                   {% if form_errors %}
                       <ul class="form__errors">
                           {% for field, errors in form_errors.items %}
                               <li>{{ field }}: {{ errors|join:", " }}</li>
                           {% endfor %}
                       </ul>
                   {% endif %}
                   <a href="{% url 'register_seeker_step1' %}" class="form__submit-btn btn-color">Повернутись до реєстрації</a>
               </div>
           </section>
        </div>
    </main>
</div>
<script src="{% static 'main/index.js' %}"></script>
</body>
</html>

just/employer/templates/employer/registration-step-2.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Головна</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/reset.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/main-employer-no-auth.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/create-vacancy.css' %}">
</head>
<body>
<div class="wrapper">
    <main>
        <div class="container">
           <section class="registration">
               <div class="registration-content">
                   <div class="stepper-wrapper">
                       <div class="stepper-item ">
                           <div class="step-counter done"><img class="check-mark" src="../../../images/check-mark.svg" alt="#"></div>
                           <div class="step-name ">Номер телефону</div>
                       </div>
                       <div class="stepper-item step-completed">
                           <div class="step-counter">2</div>
                           <div class="step-name">Підтвердження</div>
                       </div>
                       <div class="stepper-item">
                           <div class="step-counter">3</div>
                           <div class="step-name">Особисті дані</div>
                       </div>
                   </div>
                   <h3 class="form__title">Реєстрація</h3>
                   <p class="form__subtitle">На вказану пошту надіслано код</p>
                    <form method="post" action="#" class="form">
                        {% csrf_token %}
                       <div class="form__input-wrapper-registration-top-24">
                           {{ form.code.label_tag }}
                           {{ form.code }}
                       </div>

                       <p class="form__input-text">Відправити повторно через 57с.</p>
                       <div class="form__double-input-wrapper">
                           <a href="#" class="form__link-back btn-transparent">Назад</a>
                           <input type="submit" id="continue" name="continue" class="form__submit-btn btn-color" value="Продовжити">
                       </div>
                   </form>
               </div>
           </section>
        </div>
    </main>
</div>
<script src="../../../index.js"></script>
</body>
</html>