just/company/urls.py
from django.urls import path
from .views import create_vacancy, get_categories, position_autocomplete, city_autocomplete
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='company/main-employer-no-auth.html'), name='main-employer-no-auth'),
    path('vacancy/new/', create_vacancy, name='create_vacancy'),

    path('get_categories/', get_categories, name='get_categories'),
    path('position-autocomplete/', position_autocomplete, name='position-autocomplete'),
    path('city-autocomplete/', city_autocomplete, name='city-autocomplete'),

]

just/just/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from main.views import employer_login_view, seeker_login_view, home
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('searcher/', include('searcher.urls')),
    path('company/', include('company.urls')),
    path('employer/login/', employer_login_view, name='employer_login'),
    path('seeker/login/', seeker_login_view, name='seeker_login'),
    path('employer/', include('employer.urls')),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('create-resume/', include('resume.urls')),
    path('feedback/', include('feedback.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

just/company/models.py
from django.db import models
from django.conf import settings  # Це використовується для посилання на модель User
from django.utils.text import slugify
from django.utils import timezone
from main.choices import EDUCATION_LEVEL_CHOICES
from ckeditor.fields import RichTextField


class Company(models.Model):
    EMPLOYEE_CHOICES = [
        (10, 'До 10 працівників '),
        (50, 'Від 10 до 50 працівників'),
        (100, 'Від 50 до 100 працівників'),
        (250, 'Від 100 до 250 працівників'),
        (500, 'Більше 500 працівників'),
    ]

    name = models.CharField(max_length=255, verbose_name="Назва")
    number_of_employees = models.IntegerField(choices=EMPLOYEE_CHOICES, verbose_name="Кількість працівників")
    logo = models.ImageField(upload_to='logos/', verbose_name="Логотип")
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, limit_choices_to={'role': 'employer'}, on_delete=models.CASCADE, verbose_name="Адміністратор", related_name='administered_companies')
    description = models.TextField(null=True, blank=True, verbose_name="Опис")
    has_link = models.BooleanField(default=False, verbose_name="Посилання")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")

    def __str__(self):
        return self.name


class JobCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name="Назва")
    slug = models.SlugField(max_length=255, unique=True, blank=True, verbose_name="Слаг")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class JobPositionGroup(models.Model):
    name = models.CharField(max_length=255, verbose_name="Назва")

    def __str__(self):
        return self.name


class JobPosition(models.Model):
    name = models.CharField(max_length=255, verbose_name="Назва")
    name_ru = models.CharField(max_length=255, verbose_name="Назва на російській мові")
    slug = models.SlugField(max_length=255, unique=True, blank=True, verbose_name="Слаг")
    categories = models.ManyToManyField(JobCategory, related_name="job_positions_by_category", verbose_name="Категорії")
    groups = models.ManyToManyField(JobPositionGroup, related_name="job_positions_by_group", verbose_name="Групи")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    image = models.ImageField(upload_to='articles/', verbose_name='Картинка')
    author = models.CharField(max_length=255, verbose_name='Автор')
    author_position = models.CharField(max_length=255, verbose_name='Посада автора')
    publication_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Перегляди')

    def __str__(self):
        return self.title


class ArticleSection(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Текст')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='sections', verbose_name='Стаття')

    def __str__(self):
        return self.title


class CommentArticle(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments', verbose_name='Користувач')
    date_time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')

    def __str__(self):
        return self.text[:20]  # Повертає перші 20 символів коментаря


class Hashtag(models.Model):
    name = models.CharField(max_length=50, verbose_name="Хештег")

    def __str__(self):
        return self.name


class Vacancy(models.Model):
    EMPLOYMENT_TYPE_CHOICES = [
        ('full', 'Повна зайнятісь'),
        ('part', 'Неповна зайнятісь'),
        ('shift', 'Позмінна робота'),
    ]

    WORK_TYPE_CHOICES = [
        ('internship', 'Стажування/практика'),
        ('remote', 'Відалена робота'),
        ('office', 'Робота в офісі'),
        ('hybrid', 'Гібридна робота'),
    ]

    STATUS_CHOICES = [
        ('standard', 'Стандарт'),
        ('standard_plus', 'Стандарт плюс'),
        ('hot', 'Гаряча'),
        ('hidden', 'Прихована'),
    ]

    EXPERIENCE_CHOICES = [
        ('no_experience', 'Можна без досвіду'),
        ('preferred_experience', 'Досвід буде перевагою'),
        ('one_year', 'Досвід від 1-го року'),
        ('two_years', 'Досвід від 2-х років'),
        ('more_than_five_years', 'Досвід більше 5 років'),
    ]

    SCHEDULE_CHOICES = [
        ('standard_5_2', 'Стандартний графік 5/2'),
        ('shift_4_4', 'Позмінний графік 4/4'),
        ('shift_2_2_4', 'Позмінний графік 2/2/4'),
        ('shift_4_2', 'Позмінний графік 4/2'),
        ('duty_1_3', 'Чергування доба/3 вихідних'),
        ('floating', 'Плаваючий графік'),
        ('free', 'Вільний графік'),
        ('part_time', 'Підробіток (не повний день)'),
    ]

    position = models.ForeignKey(JobPosition, on_delete=models.CASCADE, related_name='vacancies', verbose_name="Посада")
    position_comment = models.CharField(max_length=30, verbose_name="Коментар до посади", blank=True, null=True)
    city = models.ForeignKey('main.City', on_delete=models.CASCADE, verbose_name="Місто")
    address = models.CharField(max_length=255, verbose_name="Адреса", blank=True, null=True)
    phone_number = models.CharField(max_length=15, verbose_name="Номер телефону", blank=True, null=True)
    min_salary = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Зарплата мін", blank=True, null=True)
    max_salary = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Зарплата макс", blank=True, null=True)
    hashtags = models.ManyToManyField(Hashtag, verbose_name="Хештеги", blank=True)
    employment_type = models.CharField(max_length=10, choices=EMPLOYMENT_TYPE_CHOICES, verbose_name="Тип зайнятості",
                                       blank=True, null=True)
    education_level = models.CharField(max_length=20, choices=EDUCATION_LEVEL_CHOICES)
    description = models.TextField(verbose_name="Опис")
    social_networks = models.BooleanField(default=False, verbose_name="Соц.Мережі")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name="Компанія")
    publication_date = models.DateTimeField(default=timezone.now, verbose_name="Дата та час публікації")
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, verbose_name="Статус")
    view_count = models.PositiveIntegerField(default=0, verbose_name="Кількість переглядів")
    experience = models.CharField(max_length=20, choices=EXPERIENCE_CHOICES, verbose_name="Досвід роботи",
                                  default='no_experience')
    schedule = models.CharField(max_length=20, choices=SCHEDULE_CHOICES, verbose_name="Графік роботи",
                                default='standard_5_2')

    def __str__(self):
        return f"{self.position} at {self.company}"


class VacancyLanguage(models.Model):
    BEGINNER = 'beginner'
    BASIC = 'basic'
    INTERMEDIATE = 'intermediate'
    ADVANCED = 'advanced'
    NATIVE = 'native'
    PROFICIENCY_LEVEL_CHOICES = [
        (BEGINNER, 'Початківець'),
        (BASIC, 'Базовий рівень'),
        (INTERMEDIATE, 'Впевнений користувач'),
        (ADVANCED, 'Вільно'),
        (NATIVE, 'Рідна'),
    ]

    language = models.ForeignKey('resume.Language', on_delete=models.CASCADE, related_name='vacancy_languages')
    proficiency_level = models.CharField(max_length=20, choices=PROFICIENCY_LEVEL_CHOICES)
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, related_name='vacancy_languages')

    def __str__(self):
        return f'{self.language.name or ""} - {self.get_proficiency_level_display() or ""}'.strip()

    class Meta:
        verbose_name = 'Vacancy Language'
        verbose_name_plural = 'Vacancy Languages'

just/vacancies/models.py
from django.db import models

# Create your models here.

just/company/forms.py
from django import forms
from .models import Vacancy, JobPosition
from main.models import City

class VacancyForm(forms.ModelForm):
    position = forms.CharField(widget=forms.TextInput(attrs={'id': 'id_position', 'class': 'form__input create-vacancy__input-size js_open universal-form'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'id': 'id_city', 'class': 'form__input create-vacancy__input-size js_open universal-form'}))
    class Meta:
        model = Vacancy
        fields = ['position', 'position_comment', 'city', 'address', 'phone_number', 'min_salary',
                  'max_salary', 'hashtags', 'employment_type', 'education_level', 'description',
                  'social_networks', 'status', 'experience', 'schedule']
        widgets = {
            'position_comment': forms.TextInput(attrs={'class': 'form__input create-vacancy__input-size',
                                                       'id': 'id_position_comment',
                                                       'placeholder': 'Нічні зміни'}),

            'address': forms.TextInput(attrs={'class': 'form__input create-vacancy__input-size'}),
            'phone_number': forms.TextInput(attrs={'class': 'form__input create-vacancy__input-size',
                                                   'id': 'id_phone_number',
                                                   'placeholder': '+380-00-00-00-000',
                                                   'type': 'tel'}),
            'min_salary': forms.NumberInput(attrs={'class': 'form__input salary__input'}),
            'max_salary': forms.NumberInput(attrs={'class': 'form__input salary__input'}),
            'hashtags': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'employment_type': forms.Select(attrs={'class': 'form-control'}),

            'description': forms.Textarea(attrs={'class': 'create-vacancy__textarea'}),
            'social_networks': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'schedule': forms.Select(attrs={'class': 'select__input'}),
        }

    def clean_position(self):
        position_name = self.cleaned_data['position']
        position = JobPosition.objects.filter(name=position_name).first()
        return position

    def clean_city(self):
        city_name = self.cleaned_data['city']
        city = City.objects.filter(name=city_name).first()
        return city  # Повертаємо об'єкт City

just/company/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms import VacancyForm
from .models import JobPosition, JobCategory
from main.models import City
import json
from django.shortcuts import redirect, render
from django.db.models import Q

def position_autocomplete(request):
    if 'term' in request.GET:
        term = request.GET.get('term')
        qs = JobPosition.objects.filter(
            Q(name__icontains=term) | Q(name_ru__icontains=term)
        )[:12]  # Обмеження до 12 записів
        positions = list(qs.values_list('name', 'name_ru'))

        # Форматування результатів для автозаповнення
        results = []
        for job in qs:
            # Спочатку перевіряємо основну назву, інакше додаємо російську назву
            if term.lower() in job.name.lower():
                results.append(job.name)
            elif job.name_ru and term.lower() in job.name_ru.lower():
                results.append(job.name_ru)

        # Видалення дублікатів та обмеження кількості результатів
        unique_results = list(dict.fromkeys(results))[:12]

        return JsonResponse(unique_results, safe=False)

def city_autocomplete(request):
    if 'term' in request.GET:
        qs = City.objects.filter(name__icontains=request.GET.get('term'))
        cities = list(qs.values_list('name', flat=True))
        return JsonResponse(cities, safe=False)


from django.core.exceptions import ValidationError


def create_vacancy(request):
    # Перевіряємо, чи користувач є роботодавцем
    if request.user.role != 'employer':
        return redirect('home')  # Замініть 'home' на вашу URL-ім'я домашньої сторінки

    # Перевіряємо, чи користувач має компанію
    if not request.user.company:
        return redirect('employer_profile')  # Замініть 'profile' на вашу URL-ім'я сторінки профілю

    if request.method == 'POST':
        form = VacancyForm(request.POST)
        if form.is_valid():
            try:
                vacancy = form.save(commit=False)
                vacancy.position = form.cleaned_data['position']
                vacancy.company = request.user.company
                vacancy.save()
                return redirect('success_page')  # Замініть 'success_page' на вашу сторінку успіху
            except Exception as e:
                form.add_error(None, f"Виникла помилка при збереженні вакансії: {str(e)}")
        else:
            form.add_error(None, "Будь ласка, виправте помилки у формі.")
    else:
        form = VacancyForm()

    return render(request, 'company/create-vacancy.html', {'form': form})


def get_categories(request):
    position_name = request.GET.get('position')
    try:
        job_position = JobPosition.objects.get(name=position_name)
        categories = job_position.categories.values('id', 'name')
        return JsonResponse({category['id']: category['name'] for category in categories})
    except JobPosition.DoesNotExist:
        return JsonResponse({"error": "JobPosition not found"}, status=404)
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)

just/vacancies/views.py
from django.shortcuts import render

# Create your views here.

just/company/templates/company/main-employer-no-auth.html
{% extends "main/base_employer.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Головна</title>
    {% block extra_styles %}
    <link rel="stylesheet" href="{% static 'main/css/main-employer-no-auth.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/create-vacancy.css' %}">
    {% endblock %}
</head>

<body>

<div class="wrapper">
    {% block content %}
    <main>
        <div class="container">
            <h1 class="main___title">Знаходьте співробітників</h1>
            <p class="main__subtitle"><span class="main__subtitle-bold">100 000</span> кандидатів з <span
                    class="main__subtitle-bold">75 000</span> резюме</p>
            <search class="search-location">
                <form action="#" class="search-location__form">
                    <div class="search-location__form-input">
                        <img src="{% static 'main/images/search-md.svg' %}" alt="search" class="search-location__form-img">
                        <label for="search" class="label-hidden">Введіть посаду</label>
                        <input type="text" id="search" name="search" class="search-location__input"
                               placeholder="Введіть посаду">
                        <div class="select__vector"></div>
                        <img src="{% static 'main/images/marker-pin-01.svg' %}" alt="cities" class="select__img">
                        <label for="city" class="label-hidden">Місто</label>
                        <select name="city" id="city" class="search-location__select">
                            <option value="city">Вся Україна</option>
                            <option value="city">Київ</option>
                            <option value="city">Львів</option>
                            <option value="city">Харків</option>
                            <option value="city">Одеса</option>
                        </select>
                    </div>
                    <button type="submit" class="search-location__btn btn-color">Знайти кандидатів</button>
                </form>
            </search>
            <section class="create-vacancy">
                <div class="main__create-vacancy-wrapper">
                    <div class="create-vacancy__block">
                        <ul class="create-vacancy__list">
                            <li class="create-vacancy__item">
                                <img class="create-vacancy__item-img" src="{% static 'main/images/ellipse-3.svg' %}" alt="ellipse">
                                <div class="create-vacancy__item-text">
                                    <p class="create-vacancy__item-title">Створіть акаунт</p>
                                    <p class="create-vacancy__item-description">Lorem ipsum dolor sit amet, consectetur
                                        adipiscing elit, sed do eiusmod tempor incididunt.
                                    </p>
                                </div>
                            </li>
                            <li class="create-vacancy__item">
                                <img class="create-vacancy__item-img" src="{% static 'main/images/ellipse-3.svg' %}" alt="ellipse">
                                <div class="create-vacancy__item-text">
                                    <p class="create-vacancy__item-title">Публікуйте вакансію</p>
                                    <p class="create-vacancy__item-description">Lorem ipsum dolor sit amet, consectetur
                                        adipiscing elit, sed do eiusmod tempor incididunt.
                                    </p>
                                </div>
                            </li>
                            <li class="create-vacancy__item">
                                <img class="create-vacancy__item-img" src="{% static 'main/images/ellipse-3.svg' %}" alt="ellipse">
                                <div class="create-vacancy__item-text">
                                    <p class="create-vacancy__item-title">Отримуйте відгуки кандидатів</p>
                                    <p class="create-vacancy__item-description">Lorem ipsum dolor sit amet, consectetur
                                        adipiscing elit, sed do eiusmod tempor incididunt.
                                    </p>
                                </div>
                            </li>
                        </ul>
                        <button class="create-vacancy__btn btn-color">Створити вакансію</button>
                    </div>
                </div>
            </section>
            <section class="main__advices">
                <div class="main__advices-wrapper">
                    <div class="advices__block-top">
                        <h2 class="advices__title">Поради та статті</h2>
                        <div class="advices-block__top-right">
                            <a href="#" class="advices-block__link">Подивитись всі</a>
                            <img src="{% static 'main/images/arrow-sm-right.svg' %}" alt="rectangle">
                        </div>
                    </div>
                    <ul class="advices__block">
                        <li class="advices__block-item">
                            <div class="advices__block-left">
                                <img src="{% static 'main/images/image-icon.svg' %}" alt="advices">
                            </div>
                            <div class="advices__block-right">
                                <p class="advices__subtitle">Як скласти вражаюче резюме:</p>
                                <p class="advices__subtitle">крок за кроком із практичними порадами</p>
                                <a href="" class="advices__link">Читати далі</a>
                            </div>
                        </li>
                        <li class="advices__block-item">
                            <div class="advices__block-left">
                                <img src="../../images/image-icon.svg" alt="advices">
                            </div>
                            <div class="advices__block-right">
                                <p class="advices__subtitle">Як скласти вражаюче резюме:</p>
                                <p class="advices__subtitle">крок за кроком із практичними порадами</p>
                                <a href="" class="advices__link">Читати далі</a>
                            </div>
                        </li>
                        <li class="advices__block-item">
                            <div class="advices__block-left">
                                <img src="../../images/image-icon.svg" alt="advices">
                            </div>
                            <div class="advices__block-right">
                                <p class="advices__subtitle">Як скласти вражаюче резюме:</p>
                                <p class="advices__subtitle">крок за кроком із практичними порадами</p>
                                <a href="" class="advices__link">Читати далі</a>
                            </div>
                        </li>
                        <li class="advices__block-item">
                            <div class="advices__block-left">
                                <img src="../../images/image-icon.svg" alt="advices">
                            </div>
                            <div class="advices__block-right">
                                <p class="advices__subtitle">Як скласти вражаюче резюме:</p>
                                <p class="advices__subtitle">крок за кроком із практичними порадами</p>
                                <a href="" class="advices__link">Читати далі</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </section>
        </div>
    </main>
    {% endblock %}
</div>

<script src="../../index.js"></script>

</body>
</html>

just/company/templates/company/vacancy_form.html
{% load crispy_forms_tags %}
{% load static %}
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Створити Вакансію</title>

</head>
<body>
    <div class="container mt-5">
        <h2>Створити Вакансію</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_position_name">Посада</label>
                {{ form.position_name }}
            </div>
            <div class="form-group">
                <label for="id_position_comment">Коментар до посади</label>
                {{ form.position_comment }}
            </div>
            <div class="form-group">
                <label for="id_city">Місто</label>
                {{ form.city }}
            </div>
            <div class="form-group">
                <label for="id_address">Адреса</label>
                {{ form.address }}
            </div>
            <div class="form-group">
                <label for="id_phone_number">Номер телефону</label>
                {{ form.phone_number }}
            </div>
            <div class="form-group">
                <label for="id_min_salary">Зарплата мін</label>
                {{ form.min_salary }}
            </div>
            <div class="form-group">
                <label for="id_max_salary">Зарплата макс</label>
                {{ form.max_salary }}
            </div>
            <div class="form-group">
                <label for="id_hashtags">Хештеги</label>
                {{ form.hashtags }}
            </div>
            <div class="form-group">
                <label for="id_employment_type">Тип зайнятості</label>
                {{ form.employment_type }}
            </div>
            <div class="form-group">
                <label for="id_work_type">Харакатер роботи</label>
                {{ form.work_type }}
            </div>
            <div class="form-group">
                <label for="id_description">Опис</label>
                {{ form.description }}
            </div>
            <div class="form-group form-check">
                {{ form.social_networks }}
                <label class="form-check-label" for="id_social_networks">Соц.Мережі</label>
            </div>
            <div class="form-group">
                <label for="id_company">Компанія</label>
                {{ form.company }}
            </div>
            <div class="form-group">
                <label for="id_status">Статус</label>
                {{ form.status }}
            </div>
            <button type="submit" class="btn btn-primary">Створити</button>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function() {
            $('#id_position_name').autocomplete({
                source: function(request, response) {
                    $.ajax({
                        url: "",
                        dataType: "json",
                        data: {
                            term: request.term
                        },
                        success: function(data) {
                            response(data);
                        }
                    });
                },
                minLength: 2,
            });
        });
    </script>
</body>
</html>